// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EncryptionManagerInterface is an autogenerated mock type for the EncryptionManagerInterface type
type EncryptionManagerInterface struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: ciphertext
func (_m *EncryptionManagerInterface) Decrypt(ciphertext []byte) ([]byte, error) {
	ret := _m.Called(ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(ciphertext)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(ciphertext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *EncryptionManagerInterface) Encrypt(plaintext []byte) ([]byte, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEncryptionManagerInterface creates a new instance of EncryptionManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptionManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptionManagerInterface {
	mock := &EncryptionManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
