// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// MQTTAuthMiddleware is an autogenerated mock type for the MQTTAuthMiddleware type
type MQTTAuthMiddleware struct {
	mock.Mock
}

// Init provides a mock function with given fields: authenticationCertificatePath
func (_m *MQTTAuthMiddleware) Init(authenticationCertificatePath string) error {
	ret := _m.Called(authenticationCertificatePath)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(authenticationCertificatePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: topic, qos, retained, payload
func (_m *MQTTAuthMiddleware) Publish(topic string, qos byte, retained bool, payload interface{}) error {
	ret := _m.Called(topic, qos, retained, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, byte, bool, interface{}) error); ok {
		r0 = rf(topic, qos, retained, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: topic, qos, callback
func (_m *MQTTAuthMiddleware) Subscribe(topic string, qos byte, callback mqtt.MessageHandler) error {
	ret := _m.Called(topic, qos, callback)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) error); ok {
		r0 = rf(topic, qos, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: topics
func (_m *MQTTAuthMiddleware) Unsubscribe(topics ...string) error {
	_va := make([]interface{}, len(topics))
	for _i := range topics {
		_va[_i] = topics[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(topics...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMQTTAuthMiddleware creates a new instance of MQTTAuthMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMQTTAuthMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MQTTAuthMiddleware {
	mock := &MQTTAuthMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
